Update cf.yml

diff --git a/.github/workflows/cf.yml b/.github/workflows/cf.yml
--- a/.github/workflows/cf.yml
+++ b/.github/workflows/cf.yml
@@ -1,106 +1,40 @@
-name: ⛅ CF Worker
+name: Upstream Sync
+
+permissions:
+  contents: write
+
 on:
-  # docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
-  # docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_dispatch
-  # docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
+  schedule:
+    - cron: "0 0 * * *" # every day
   workflow_dispatch:
-    # github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
-    # docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
-    inputs:
-      # docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_dispatchinputs
-      environment:
-        description: 'wrangler env to deploy to'
-        required: true
-        default: 'dev'
-        type: choice
-        options:
-        - dev
-        - prod
-        - one
-      commit:
-        description: 'git tip commit to deploy'
-        default: 'main'
-        required: true
-
-  push:
-    # TODO: inputs.environment and inputs.commit
-    branches:
-      - "main"
-    tags:
-      - "v*"
-    paths-ignore:
-      - ".github/**"
-      - "!.github/workflows/cf.yml"
-      - ".env.example"
-      - ".eslintrc.cjs"
-      - ".prettierignore"
-      - "fly.toml"
-      - "README.md"
-      - "node.Dockerfile"
-      - "deno.Dockerfile"
-      - "import_map.json"
-      - ".vscode/*"
-      - ".husky/*"
-      - ".prettierrc.json"
-      - "LICENSE"
-      - "run"
-  repository_dispatch:
-
-env:
-  GIT_REF: ${{ github.event.inputs.commit || github.ref }}
-  # default is 'dev' which is really empty/no env
-  WORKERS_ENV: ''
 
 jobs:
-  deploy:
-    name: 🚀 Deploy worker
+  sync_latest_from_upstream:
+    name: Sync latest commits from upstream repo
     runs-on: ubuntu-latest
-    timeout-minutes: 60
+    if: ${{ github.event.repository.fork }}
+
     steps:
-      - name: Checkout
-        uses: actions/checkout@v3.3.0
+      # Step 1: run a standard checkout action
+      - name: Checkout target repo
+        uses: actions/checkout@v3
+
+      # Step 2: run the sync action
+      - name: Sync upstream changes
+        id: sync
+        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
         with:
-          ref: ${{ env.GIT_REF }}
-          fetch-depth: 0
+          upstream_sync_repo: cmliu/WorkerVless2sub
+          upstream_sync_branch: main
+          target_sync_branch: main
+          target_repo_token: ${{ secrets.GITHUB_TOKEN }} # automatically generated, no need to set
 
-      - name: 🛸 Env?
-        # 'dev' env deploys to default WORKERS_ENV, which is, '' (an empty string)
-        if: github.event.inputs.environment == 'prod' || github.event.inputs.environment == 'one'
+          # Set test_mode true to run tests instead of the true action!!
+          test_mode: false
+
+      - name: Sync check
+        if: failure()
         run: |
-          echo "WORKERS_ENV=${WENV}" >> $GITHUB_ENV
-          echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_ENV
-        shell: bash
-        env:
-          WENV: ${{ github.event.inputs.environment }}
-          COMMIT_SHA: ${{ github.sha }}
-
-      - name: 🎱 Tag?
-        # docs.github.com/en/actions/learn-github-actions/contexts#github-context
-        if: github.ref_type == 'tag'
-        run: |
-          echo "WORKERS_ENV=${WENV}" >> $GITHUB_ENV
-          echo "COMMIT_SHA=${COMMIT_SHA}" >> $GITHUB_ENV
-        shell: bash
-        env:
-          # tagged deploys always deploy to prod
-          WENV: 'prod'
-          COMMIT_SHA: ${{ github.sha }}
-
-        # npm (and node16) are installed by wrangler-action in a pre-job setup
-      - name: 🏗 Get dependencies
-        run: npm i
-
-      - name: 📚 Wrangler publish
-        # github.com/cloudflare/wrangler-action
-        uses: cloudflare/wrangler-action@2.0.0
-        with:
-          apiToken: ${{ secrets.CF_API_TOKEN }}
-          # input overrides env-defaults, regardless
-          environment: ${{ env.WORKERS_ENV }}
-        env:
-          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
-          GIT_COMMIT_ID: ${{ env.GIT_REF }}
-
-      - name: 🎤 Notice
-        run: |
-          echo "::notice::Deployed to ${WORKERS_ENV} / ${GIT_REF} @ ${COMMIT_SHA}"
+          echo "[Error] 由于上游仓库的 workflow 文件变更，导致 GitHub 自动暂停了本次自动更新，你需要手动 Sync Fork 一次，详细教程请查看项目README.md "
+          echo "[Error] Due to a change in the workflow file of the upstream repository, GitHub has automatically suspended the scheduled automatic update. You need to manually sync your fork. Please refer to the project README.md for instructions. "
+          exit 1
